server:
  port: 8989

spring:
  application:
    name: psa-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/SCRBJAIPUR/psa-config-server-repo
          skipSslValidation: true
