#spring:
#  application:
#    name: PSA-COMMUNITY-SERVICE

#eureka:
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl.defaultZone: http://10.68.238.4:8761/eureka